"""Events in schames

Revision ID: 04e984c32b4e
Revises: a2482d506896
Create Date: 2023-12-27 10:17:11.799576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04e984c32b4e'
down_revision: Union[str, None] = 'a2482d506896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('location_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'location_address')
    # ### end Alembic commands ###
