"""id for token table added

Revision ID: 090459d5e102
Revises: 1403f7fd69ad
Create Date: 2023-12-24 22:05:45.687615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '090459d5e102'
down_revision: Union[str, None] = '1403f7fd69ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'id')
    # ### end Alembic commands ###
