"""Initialize table

Revision ID: 0bef7250b316
Revises: 3df470d5c12f
Create Date: 2023-12-25 11:22:48.119474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bef7250b316'
down_revision: Union[str, None] = '3df470d5c12f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_choices_choice_text', table_name='choices')
    op.drop_index('ix_choices_id', table_name='choices')
    op.drop_table('choices')
    op.drop_index('ix_questions_id', table_name='questions')
    op.drop_index('ix_questions_question_text', table_name='questions')
    op.drop_table('questions')
    op.add_column('users', sa.Column('email', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(length=200), nullable=False))
    op.add_column('users', sa.Column('role', sa.String(length=20), server_default='user', nullable=False))
    op.add_column('users', sa.Column('age', sa.String(length=3), server_default='18', nullable=False))
    op.add_column('users', sa.Column('address', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'address')
    op.drop_column('users', 'age')
    op.drop_column('users', 'role')
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    op.create_table('questions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('questions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('question_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='questions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_questions_question_text', 'questions', ['question_text'], unique=False)
    op.create_index('ix_questions_id', 'questions', ['id'], unique=False)
    op.create_table('choices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('choice_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='choices_question_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='choices_pkey')
    )
    op.create_index('ix_choices_id', 'choices', ['id'], unique=False)
    op.create_index('ix_choices_choice_text', 'choices', ['choice_text'], unique=False)
    # ### end Alembic commands ###
