"""Added Notification model

Revision ID: 0e7301d61867
Revises: f0aa55d83335
Create Date: 2024-01-03 14:44:56.545781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e7301d61867'
down_revision: Union[str, None] = 'f0aa55d83335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('notification_type', sa.Enum('EventLiked', 'EventInterested', 'EventCreated', name='notificationtype'), nullable=False))
    op.add_column('notifications', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.drop_index('ix_notifications_id', table_name='notifications')
    op.drop_index('ix_notifications_message', table_name='notifications')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_index('ix_notifications_message', 'notifications', ['message'], unique=False)
    op.create_index('ix_notifications_id', 'notifications', ['id'], unique=False)
    op.drop_column('notifications', 'created_date')
    op.drop_column('notifications', 'notification_type')
    op.drop_column('notifications', 'user_id')
    # ### end Alembic commands ###
