"""Drop token table

Revision ID: 15470c9d4020
Revises: a97f9f51652b
Create Date: 2023-12-27 09:23:04.344618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15470c9d4020'
down_revision: Union[str, None] = 'a97f9f51652b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('access_toke', sa.VARCHAR(length=450), autoincrement=False, nullable=False),
    sa.Column('refresh_toke', sa.VARCHAR(length=450), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
