"""Login changes

Revision ID: 27b414c33ab0
Revises: a909a5c24a2e
Create Date: 2023-12-27 09:07:11.552242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27b414c33ab0'
down_revision: Union[str, None] = 'a909a5c24a2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('interested_genre', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('refresh_token', sa.String(length=450), nullable=False))
    op.add_column('users', sa.Column('refresh_token_expiry', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_date')
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    op.drop_column('users', 'refresh_token_expiry')
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'interested_genre')
    # ### end Alembic commands ###
