"""schema updated

Revision ID: 901f626559fc
Revises: 7d900137f73b
Create Date: 2023-12-25 09:19:01.398889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '901f626559fc'
down_revision: Union[str, None] = '7d900137f73b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('refresh_token', sa.String(length=450), nullable=False))
    op.add_column('token', sa.Column('expiry_date', sa.DateTime(), nullable=False))
    op.alter_column('token', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_column('token', 'refresh_toke')
    op.drop_column('token', 'access_toke')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('access_toke', sa.VARCHAR(length=450), autoincrement=False, nullable=False))
    op.add_column('token', sa.Column('refresh_toke', sa.VARCHAR(length=450), autoincrement=False, nullable=False))
    op.alter_column('token', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('token', 'expiry_date')
    op.drop_column('token', 'refresh_token')
    # ### end Alembic commands ###
