"""Changes in schames

Revision ID: a2482d506896
Revises: 15470c9d4020
Create Date: 2023-12-27 10:12:25.698173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2482d506896'
down_revision: Union[str, None] = '15470c9d4020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('genre', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'genre')
    # ### end Alembic commands ###
