"""Updated token table

Revision ID: ae8b73cba5eb
Revises: 2d9e30ebeec3
Create Date: 2023-12-25 10:00:13.685341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae8b73cba5eb'
down_revision: Union[str, None] = '2d9e30ebeec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
