"""schema updated

Revision ID: d7ca66fe0b64
Revises: efbfa9de7d53
Create Date: 2023-12-25 09:41:56.404352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7ca66fe0b64'
down_revision: Union[str, None] = 'efbfa9de7d53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('access_toke', sa.String(length=450), nullable=False))
    op.add_column('token', sa.Column('refresh_toke', sa.String(length=450), nullable=False))
    op.drop_column('token', 'id')
    op.drop_column('token', 'expiry_date')
    op.drop_column('token', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('refresh_token', sa.VARCHAR(length=450), autoincrement=False, nullable=False))
    op.add_column('token', sa.Column('expiry_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('token', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('token', 'refresh_toke')
    op.drop_column('token', 'access_toke')
    # ### end Alembic commands ###
