"""Your migration message

Revision ID: dfada4f78a52
Revises: 
Create Date: 2023-12-24 12:10:10.852259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfada4f78a52'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persons')
    op.add_column('users', sa.Column('role', sa.String(length=20), server_default='user', nullable=False))
    op.add_column('users', sa.Column('age', sa.String(length=3), nullable=False))
    op.add_column('users', sa.Column('address', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address')
    op.drop_column('users', 'age')
    op.drop_column('users', 'role')
    op.create_table('persons',
    sa.Column('personid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lastname', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('firstname', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
