"""schema updated

Revision ID: efbfa9de7d53
Revises: 901f626559fc
Create Date: 2023-12-25 09:28:30.103177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efbfa9de7d53'
down_revision: Union[str, None] = '901f626559fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('token', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('token', 'id')
    # ### end Alembic commands ###
