"""Updated token table

Revision ID: f64c90fddb14
Revises: ae8b73cba5eb
Create Date: 2023-12-25 10:43:53.162443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f64c90fddb14'
down_revision: Union[str, None] = 'ae8b73cba5eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('organizer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event', 'users', ['organizer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'organizer_id')
    # ### end Alembic commands ###
